import random
import io
import numpy as np
import streamlit as st
from PIL import Image, ImageEnhance, ImageOps, ImageFilter

st.set_page_config(
    page_title="ブレてからが本番。",
    page_icon="📸",
    layout="centered"
)

st.markdown("""
<style>
    .stApp {
        background-color: #0d0f19;
        color: #fafaef;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    }
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        letter-spacing: -0.04em;
        background: linear-gradient(135deg, #e6ff6f 0%, #a335f7 50%, #0ec499 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0px;
    }
    .sub-title {
        color: #9ca3af;
        font-size: 0.95rem;
        margin-bottom: 2rem;
        font-weight: 400;
    }
    .step-header {
        font-weight: 700;
        font-size: 1.05rem;
        color: #e5e7eb;
        margin-top: 2rem;
        margin-bottom: 0.75rem;
        letter-spacing: -0.01em;
    }
    [data-testid="stFileUploader"] {
        background-color: #111827;
        border: 1px dashed #374151;
        border-radius: 12px;
        padding: 1rem;
    }
    [data-testid="stFileUploader"]:hover {
        border-color: #6366f1;
    }
    .stButton button {
        background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%);
        color: white;
        border: none;
        border-radius: 10px;
        font-weight: 600;
        padding: 0.8rem 1rem;
        box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
        transition: all 0.2s ease;
        width: 100%;
    }
    .stButton button:hover {
        background: linear-gradient(135deg, #4338ca 0%, #6d28d9 100%);
        box-shadow: 0 6px 16px rgba(99, 102, 241, 0.4);
        transform: translateY(-1px);
    }
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="main-title">ブレてからが本番。 <span style="font-size: 1.2rem;">✨</span></p>', unsafe_allow_html=True)
st.markdown('<p class="sub-title">微小なブレから、皆が目を引く強烈な1枚へ！失敗作を高衝撃変形エンジンでランダムアップサイクル。</p>', unsafe_allow_html=True)

def apply_impact_art_random(image):
    # 常に確実に3チャンネルのRGBモードに変換
    if image.mode != "RGB":
        image = image.convert("RGB")
    
    # コントラストと発色を強烈にブースト
    image = ImageEnhance.Contrast(image).enhance(random.uniform(2.5, 3.5))
    image = ImageEnhance.Color(image).enhance(random.uniform(2.0, 3.0))
    image = image.convert("RGB")
    
    styles = ["グリッチ・ポップ", "ネオン・フロー", "抽象的破片", "カラーウェーブ"]
    chosen_style = random.choice(styles)
    
    if chosen_style == "グリッチ・ポップ":
        edges = image.filter(ImageFilter.FIND_EDGES).convert("RGB")
        inverted = ImageOps.invert(edges).convert("RGB")
        image = Image.blend(image, inverted, alpha=random.uniform(0.4, 0.7))
        image = image.filter(ImageFilter.SHARPEN)
        
    elif chosen_style == "ネオン・フロー":
        blurred = image.filter(ImageFilter.GaussianBlur(radius=random.randint(3, 6)))
        edges = image.filter(ImageFilter.FIND_EDGES).convert("RGB")
        image = Image.blend(blurred, edges, alpha=random.uniform(0.5, 0.8))
        # ソラリゼーション後に強制的にRGB化（Lモード化を防ぐ）
        image = ImageOps.solarize(image, threshold=random.randint(80, 140)).convert("RGB")
        
    elif chosen_style == "抽象的破片":
        image = image.filter(ImageFilter.DETAIL)
        edges = image.filter(ImageFilter.FIND_EDGES).convert("RGB")
        image = Image.blend(image, edges, alpha=random.uniform(0.3, 0.6))
        image = ImageOps.solarize(image, threshold=100).convert("RGB")
        
    elif chosen_style == "カラーウェーブ":
        for _ in range(random.randint(1, 3)):
            image = image.filter(ImageFilter.SMOOTH_MORE)
        image = ImageOps.solarize(image, threshold=128).convert("RGB")
        image = ImageEnhance.Brightness(image).enhance(random.uniform(1.2, 1.5))
        
    # 最終的な戻り値も確実にRGB
    return image.convert("RGB"), chosen_style

st.markdown('<p class="step-header">ステップ1: 失敗写真をアップロード</p>', unsafe_allow_html=True)
uploaded_file = st.file_uploader("", type=["jpg", "jpeg", "png", "webp", "heic", "heif"])

if uploaded_file is not None:
    try:
        original_image = Image.open(uploaded_file)
    except Exception as e:
        st.error(f"画像の読み込みに失敗しました。別の画像でお試しください。（エラー: {e}）")
        st.stop()
    
    st.markdown("<br>", unsafe_allow_html=True)
    
    if st.button("🎲 ガチャを回して強烈な1枚を生成する"):
        with st.spinner("高衝撃変形エンジン（ガチャ）作動中... 🚀"):
            processed_image, active_style = apply_impact_art_random(original_image)
            
            # 念のためもう一度PIL画像から直接RGBのNumPy配列を安全に作成
            img_array = np.array(processed_image.convert("RGB"))
            
        st.success(f"✨ 演出スタイル「{active_style}」で強烈な1枚が降臨しました！")
        
        st.image(img_array, caption=f"Generated by 高衝撃変形エンジン ({active_style})", use_column_width=True)
        
        buf = io.BytesIO()
        processed_image.save(buf, format="PNG")
        byte_im = buf.getvalue()
        
        st.download_button(
            label="📥 この強烈な1枚をダウンロード (PNG)",
            data=byte_im,
            file_name=f"bure-kara-impact-gacha.png",
            mime="image/png"
        )
else:
    st.info("💡 まずはスマホのブレた写真を選択してください。ボタンを押すたびに、ランダムで予測不可能な強烈アートに生まれ変わります！")
